typography_spectrum: 0.4505476709505967
content_rating:
  adult: false
color:
  lightness: 0.9380125400736596
  brandColors:
    - '#543463'
    - '#62540B'
    - '#C74716'
    - '#FFFFD3'
    - '#D29B70'
  saturation: 0.1677078891825853
  brandStrength: 0.4365451392207737
  rhythmicContrast: 0.3171928898647132
github: true
opengraph: {}
layout_spectrum: 0.045440686877798474
analytics: {}
author:
  name: Shaun Nelson
  email: shaun@opusikon.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/64cb7981-af3d-4c64-84c4-00678c6086d8.png
name: 'opus ikon, a collaborative group - making deals faster © 2017'
url: 'http://opusicon.com'
navigation:
  - name: WHO we are and WHY we care
    id: 0a1fc343-7a16-4ab1-9e8c-f7bd02c73afb
    type: content
  - name: WHAT we do
    id: b3bb63b8-9e2c-4f75-abf0-cf57612cc240
    type: content
  - name: HOW we do it
    id: fd9aa9c3-4fc5-43b2-8434-cd56052ae317
    type: content
  - name: WHEN we'd like to do it again
    id: 5009740a-5935-47a6-a0b4-5d061686a1f5
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: opus ikon design
content: []
description: the Art of the Deal
purpose:
  - type: email
    url: 'mailto:hello@opusicon.com'
    label: clarity in chaos
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/66e927aa-0f0f-4076-a1a3-823e77da8abd.png
