typography_spectrum: 0.4505476709505967
content_rating:
  adult: false
color:
  lightness: 0.9380125400736596
  brandColors:
    - '#543463'
    - '#62540B'
    - '#C74716'
    - '#FFFFD3'
    - '#D29B70'
  saturation: 0.1677078891825853
  brandStrength: 0.4365451392207737
  rhythmicContrast: 0.3171928898647132
github: true
opengraph: {}
layout_spectrum: 0.045440686877798474
analytics: {}
author:
  name: Shaun Nelson
  email: shaun@opusicon.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/eeb8d994-155f-4092-a010-b4298a472ac3.png
name: Opus Icon Advisory Group
url: 'http://opusicon.com'
navigation:
  - name: WHO we are and WHY we care
    id: 0a1fc343-7a16-4ab1-9e8c-f7bd02c73afb
    type: content
  - name: WHAT we do
    id: b3bb63b8-9e2c-4f75-abf0-cf57612cc240
    type: content
  - name: HOW we do it
    id: fd9aa9c3-4fc5-43b2-8434-cd56052ae317
    type: content
  - name: WHEN we'd like to do it again
    id: 5009740a-5935-47a6-a0b4-5d061686a1f5
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: the art of the deal
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="http://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FRLn1ErhxOPo%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DRLn1ErhxOPo&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FRLn1ErhxOPo%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: stepvideolabs
          url: 'https://www.youtube.com/user/stepvideolabs'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      keywords:
        - slow motion water drop
        - slow motion water drop hd
        - surface tension of water
        - water ripples slow motion
        - water dropping slow motion
        - water droplets slow motio...
      description: >-
        Slow Motion Water Droplet Falling Breaks Surface Tension and Makes
        Ripples in HD High Definition YouTube Video View. The equipment used for
        this shot was an award winning Phantom HD Gold digital high speed
        camera. Slow motion (often abbreviated as slowmo) is photographic effect
        in film-making whereby time appears to be slowed down.
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=RLn1ErhxOPo&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=RLn1ErhxOPo&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=RLn1ErhxOPo&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=RLn1ErhxOPo&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=RLn1ErhxOPo&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=RLn1ErhxOPo'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=RLn1ErhxOPo
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=RLn1ErhxOPo
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'http://www.youtube.com/watch?v=RLn1ErhxOPo'
      title: >-
        Slow Motion Water Droplet Falling Breaks Surface Tension and Makes
        Ripples in HD YouTube Video View
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: focus is what's revealed when the unimportant is hidden
purpose:
  - type: email
    url: 'mailto:hello@opusicon.com'
    label: click to see how we can bring order to chaos
