layout_spectrum: 0.7858492539349096
typography_spectrum: 0.8890892647605131
color:
  lightness: 0.15250916495587272
  brandColors:
    - '#543463'
    - '#62540B'
    - '#C74716'
    - '#FFFFD3'
    - '#D29B70'
  saturation: 0.16615873715222473
  brandStrength: 0.04899064726435976
  rhythmicContrast: 0.13032172243037068
name: Opus Icon | an advisory group |
analytics: {}
purpose:
  - type: email
    url: 'mailto:hello@opusicon.com'
    label: Get in touch with us
description: >-
  "focus" isn’t a product to be created; it’s  what's revealed when the
  unimportant is blurred  …  ~ OPUS ICON
author:
  name: Shaun Nelson
  email: shaun@opusicon.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/e2d36935-6c23-4789-8036-7ea1ccbebfe3.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/e2d36935-6c23-4789-8036-7ea1ccbebfe3.jpg
    metadata:
      author: []
      datePublished: null
      keywords: []
      '@type': MediaObject
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
      related: []
      app_links: []
      '@context': 'http://schema.org'
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
navigation:
  - name: who we are
    id: 0a1fc343-7a16-4ab1-9e8c-f7bd02c73afb
    type: content
  - name: what we do
    id: b3bb63b8-9e2c-4f75-abf0-cf57612cc240
    type: content
  - name: how we do it
    id: fd9aa9c3-4fc5-43b2-8434-cd56052ae317
    type: content
content_rating:
  adult: false
opengraph: {}
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/eeb8d994-155f-4092-a010-b4298a472ac3.png
title: the artful barter of ideas and time
url: 'http://opusicon.com'
github: true
