layout_spectrum: 0.045440686877798474
typography_spectrum: 0.4505476709505967
color:
  lightness: 0.9380125400736596
  brandColors:
    - '#543463'
    - '#62540B'
    - '#C74716'
    - '#FFFFD3'
    - '#D29B70'
  saturation: 0.1677078891825853
  brandStrength: 0.4365451392207737
  rhythmicContrast: 0.3171928898647132
name: Opus Icon Advisory Group
analytics: {}
purpose:
  - type: email
    url: 'mailto:hello@opusicon.com'
    label: click to see how we can bring order to chaos
description: focus is what's revealed when the unimportant is hidden
author:
  name: Shaun Nelson
  email: shaun@opusicon.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="http://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F2bUj-RtbqyI%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D2bUj-RtbqyI&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F2bUj-RtbqyI%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Video Motion Rolodex
          url: 'https://www.youtube.com/channel/UCAdoSZai0e6aFq0IOr6Fx_w'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      keywords:
        - landing page monkey
        - background videos
        - video backgrounds
        - video loops
        - free
        - free video loops
        - free video backgrounds
        - motion video backgrounds hd
        - video lo...
      description: >-
        Video Motion Rolodex Beach Coast for Landing Page Monkey "Need a quick
        video background for your next Landing Page Monkey Page?" Okay we've
        found cool motion backgrounds you can use in any of your projects and
        put them together in a handy Rolodex The videos listed are all found on
        YouTube (you'll find potentially thousands more if you search 'video
        loop', 'motion background' etc.
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=2bUj-RtbqyI&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=2bUj-RtbqyI&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=2bUj-RtbqyI&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=2bUj-RtbqyI&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=2bUj-RtbqyI&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=2bUj-RtbqyI'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=2bUj-RtbqyI
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=2bUj-RtbqyI
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'http://www.youtube.com/watch?v=2bUj-RtbqyI'
      title: Video Motion Rolodex Beach Coast for Landing Page Monkey
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
navigation:
  - name: who we are
    id: 0a1fc343-7a16-4ab1-9e8c-f7bd02c73afb
    type: content
  - name: what we do
    id: b3bb63b8-9e2c-4f75-abf0-cf57612cc240
    type: content
  - name: how we do it
    id: fd9aa9c3-4fc5-43b2-8434-cd56052ae317
    type: content
content_rating:
  adult: false
opengraph: {}
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/eeb8d994-155f-4092-a010-b4298a472ac3.png
title: 'dealing in art, the art of the deal'
url: 'http://opusicon.com'
github: true
