layout_spectrum: 0.04817625151974804
typography_spectrum: 0.17246942565213927
color:
  lightness: 0.9355282119348055
  brandColors:
    - '#543463'
    - '#62540B'
    - '#C74716'
    - '#FFFFD3'
    - '#D29B70'
  saturation: 0.794687751392087
  brandStrength: 0.49015355456887866
  rhythmicContrast: 0.3135259572991935
content_rating:
  adult: false
github: true
opengraph: {}
analytics: {}
author:
  name: Shaun Nelson
  email: shaun@opusikon.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/26f10acb-78be-4ff5-b4d7-c8ed1ce2999b.png
name: 'opus ikon, a collaborative group - making deals faster © 2017'
url: 'http://opusicon.com'
navigation:
  - name: WHY we do it
    id: 0a1fc343-7a16-4ab1-9e8c-f7bd02c73afb
    type: content
  - name: WHAT we do
    id: b3bb63b8-9e2c-4f75-abf0-cf57612cc240
    type: content
  - name: HOW we do it
    id: fd9aa9c3-4fc5-43b2-8434-cd56052ae317
    type: content
  - name: WHEN we'd like to do it again
    id: 5009740a-5935-47a6-a0b4-5d061686a1f5
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/66e927aa-0f0f-4076-a1a3-823e77da8abd.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: opus ikon design
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="http://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FBgpUVde196k%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DBgpUVde196k&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FBgpUVde196k%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'http://www.youtube.com/watch?v=BgpUVde196k'
      keywords:
        - video
        - sharing
        - camera phone
        - video phone
        - free
        - upload
      related: []
      author:
        - name: Josu Relax
          url: 'https://www.youtube.com/channel/UC3Lnn-nMtHueWyesrDBfZ8g'
          avatar: {}
      '@context': 'http://schema.org'
      title: Blue Water Texture Particles Moving | 4K Relaxing Screensaver
      '@type': VideoObject
      app_links: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      description: >-
        Website: http://www.relaxing-videos.ga This 2160p video of xxx with no
        audio will allow you transform your computer, tablet or smartphone
        screen in a beautiful viewpoint, screensaver or live wallpaper of this
        xxx. It will make you relax and feel calm and it is the perfect
        background when you are not using the PC or even when you are studying
        and want to concentrate.
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: the Art of Visualization
purpose:
  - type: email
    url: 'mailto:hello@opusicon.com'
    label: clarity in chaos
